name: CICD

on:
 push:

jobs:
   test:
     runs-on: ubuntu-latest 
     steps:
      - uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Build services
        run: doocker compose -f docker-compose.test.yml up -d --build

      - name: Healthcheck 
        run: |
         sleep 30 
         if curl -f https://localhost:3000/api/v1/health; then
          echo "app is working"
         else
           echo "Test failed"
           docker compose logs
           exit 1 
         fi

      - name: Cleanup
        run: docker compose down 